### ISSUE TITLE
Populated skill tree link doesn't work on PoE website

### ISSUE THREAD

**Issue by rowolff** [EmmittJ/PoESkillTree#159] opened 2015-07-12 10:19 UTC
It works vice verca, you create a build on the PoE website and it loads fine into the PoESkilTree. But when you modify it in the program and then copy & paste the link back to the browser, the PoE website reports:

"The build you are trying to load is using an old version of the passive tree and will not work."

**Comment by SpaceOgre** [comment] 2015-07-12 10:26
Did a fast check and the problem is this: GGG have changed the class code of the link.
Old Witch: AAAAAgMA
New Witch: AAAAAwMA

It is the same for all links eg. g -> w

So atm you can just change that part manually.

**Comment by SpaceOgre** [comment] 2015-07-12 11:12
Fixed in: 30d230c1fe603214cd5f5d2d14f2bbe961e4f23d

**Closed by SpaceOgre** 2015-07-12 11:12 UTC
