### ISSUE TITLE
Ascendancy support

### ISSUE THREAD

**Issue by MLanghof** [EmmittJ/PoESkillTree#219] opened 2015-11-21 01:45 UTC
Well, [Ascendancy](http://www.pathofexile.com/ascendancy) is coming, and with it lots of new mods and a whole new... chunk of the skill tree.

My thoughts so far:
* The ascendancies' trees (I'll call them subtrees) will need to be toggleable, and with them node highlights, mouseover things etc.
* I'm curious how the website will do it, we should probably mirror the behavior.
* Enforcing the 6 point limit on those subtrees shouldn't be particularly challenging.
* Inclusion of this stuff in the skill tree optimizer and generator is basically just additional preprocessing.

**Comment by EmmittJ** [comment] 2015-11-21 02:35
Just a quick note, there is no need to limit the node count. We don't do
this currently.

**Comment by brather1ng** [comment] 2015-11-21 13:12
I would say the general UI part is not too hard. Just make it a toggable overlay were you see the Ascendany skill tree and can switch between the three for the selected class.

I see the problem at mirroring the behavior of the main skill tree for those smaller ones (assuming what the official website gives us is similar to what it gives for the main skill tree) because the current skill tree stuff is not written in a way were it could easily be changed to also produce the smaller ones (well, except copy-pasting the whole skill tree code and changing what needs to be changed, but I doubt that is a good idea).

But I guess it is too early to make assumptions on what the official website supplies us with. Maybe some refactoring of the skill tree code to make it more modular could be done at this point in time.

**Comment by MLanghof** [comment] 2015-11-21 18:45
> But I guess it is too early to make assumptions on what the official website supplies us with. Maybe some refactoring of the skill tree code to make it more modular could be done at this point in time.

I was thinking about that too. Compared to the website, we have the additional problematic of node highlights (what if a node behind the subtree is highlighted)? There are of course solutions for this (draw order?), but we'll have to cleanly separate the drawing/display code from the internal representation (those subtrees still have points allocated even if they're not being rendered).

**Comment by brather1ng** [comment] 2015-11-21 18:56
If the UI is properly done and those subtrees are entirely separated from the main tree that shouldn't be much of a problem. For example, you don't see highlights through the "Attributes" overlay. But, as you said, this will require separation of internal representation and the ui code, which is the reason the skill tree code as it is now won't work for subtrees.

**Comment by brather1ng** [comment] 2016-02-25 22:08
Well, things are getting a lot more interesting than I thought.

I guess a rather easy first step would be to ignore the Ascendancy classes themselves and just throw a button somewhere that enables taking unconnected nodes. For the ascendancy classes we will have to see what the officical JSON looks like.

**Comment by EmmittJ** [comment] 2016-02-25 22:10
Yep, once we get the data I will just make it work for the base tree and
move onto Ascendancy classes after.

**Comment by MLanghof** [comment] 2016-02-25 23:36
I think the "unconnected nodes" should be somewhat easy to do. Add the connection between scion start and the other class start nodes, insert a check in the drawing code so no path is drawn/highlighted, add a check in the click-handler to only allow allocating the other starting nodes if the respective ascendancy node is taken.

**Comment by l0g0sys** [comment] 2016-02-26 05:30
My guess is that we won't even need support for unconnected nodes, but 
rather multiple tree support. Main tree + subclass trees each having own 
starting nodes etc.
But we will see from data how they are defined.

**Comment by SpaceOgre** [comment] 2016-02-26 07:20
Yeah, it is better to wait for the official data format. But starting on
the new windows/overlays is not so bad, unless we want to replicate the
look from the official tree. My guess is that it will probably work more or
less like in game.

**Comment by EmmittJ** [comment] 2016-02-26 07:24
I was thinking about doing something similar to however it is officially
displayed. I guess we will find out

**Comment by brather1ng** [comment] 2016-02-26 13:04
Making a checkbox for skilling unconnected nodes was more meant as a temporary solution until we have proper support for ascendancy classes (it would completely ignore ascendancy classes).

With that, people could start planning Scion builds pretty much the moment we support the new skill tree data (if it's not harder than I think). I'd imagine having some kind of ascendancy class support will take a while.

And it would also be a (pretty dirty) way of "supporting" Intuitive Leap jewels.

**Comment by MLanghof** [comment] 2016-02-26 13:08
Speaking of Intuitive Leap, it might actually be a decent idea to add just general "on-the-fly" invisible node connections for this purpose. If they are kept separate from the "default" ones, then handling them should be quite manageable and they could be reused for multiple purposes.

**Comment by brather1ng** [comment] 2016-02-27 01:02
Doesn't look like doing it properly is too hard (those drawn connections obviously have to go):
![skilling](https://cloud.githubusercontent.com/assets/7596346/13369417/ac4da124-dcf4-11e5-8646-f72eaa320324.PNG)
This is how the class for the additional start is selected currently:
![selection](https://cloud.githubusercontent.com/assets/7596346/13369427/e43d7546-dcf4-11e5-8e4e-c73a324e1762.PNG)

The nodes adjacent to the start of the other class are simply added to those of the Scion start node (and vice versa). A better way (as @MLanghof noted) would be to keep them separate from the normal connections.

(I tried the dirty way with just a checkbox, works too but totally fucks up our node refunding stuff)

**Comment by EmmittJ** [comment] 2016-03-05 20:51
I think this has been solved unless anyone has anything else to add?

**Comment by brather1ng** [comment] 2016-03-05 20:57
Having the ascendancy trees included like they are ingame would be a nice to have feature. But besides that all the ascendancy stuff is done, I think.

**Comment by EmmittJ** [comment] 2016-03-05 21:00
Ah, that just requires another drop down. I am thinking of displaying the Ascendancy classes in two ways.
1) A more cleaned up version of what they are now
2) In game toggle on/off Ascendancy classes

**Comment by EmmittJ** [comment] 2016-03-05 21:00
This would be optional to the user via a setting

**Comment by brather1ng** [comment] 2016-03-05 21:04
I like the way it's done ingame. Imo the way it is now is cluttering the UI because all classes are always shown. But it would also require a dropdown somewhere to select your ascendancy class.

Or do you mean having both (your 1 and 2) implemented and the user can switch between them?

**Comment by EmmittJ** [comment] 2016-03-05 21:07
The user would be able to switch between them. Cleaning up the drawing
(should be) easy. It is a matter of changing the Node Group position.

A drop-down selection box will have to be made for the ascendancy classes
with None (or blank) as a default option.

**Comment by EmmittJ** [comment] 2016-03-24 21:32
![New Skill Points](http://i.imgur.com/RLcG3Sk.png)
What do you guys think of adding a skill point display like this?
Left is used and Right is total, these are all updating dynamically (except base of 123 and 6)

**Comment by SpaceOgre** [comment] 2016-03-28 10:49
I think that it is a good idea.

**Comment by EmmittJ** [comment] 2016-04-01 06:21
Hey guys, sorry for all the commits these last couple days. I have been working on the ascendancy classes being displayed properly. They should now be displayed in two ways: 1) the current way where all the classes are shown by default, and 2) the way they are officially displayed. I am sorry that the code to draw the ascendancy classes is so sloppy, and I want to look into different ways to draw everything. The problem is not all of the ascendancy nodes are in the same group, so each group needs to be re-positioned once the start node is re-positioned.  

There some bugs that I will work on like checking/un-checking the setting should redraw the ascendancy classes, and returning ascendancy classes to their original positions. Other than that I think we have full ascendancy support.

**Comment by SpaceOgre** [comment] 2016-04-01 07:17
No problem, for my part it is good to see when someone is working on something so I don't do the same.

Have had a look and I think I have some ideas to boost performance when toggling the ascendancy tree with the button, but I don't want to start until you feel you are finished since you might already have plans for this.

**Comment by EmmittJ** [comment] 2016-04-01 07:27
Separating out the drawing code for ascendancy classes should improve
performance a lot. I was just getting it to work with decent performance.
The draw code in general is pretty awful, but it is something I haven't
been able to test other solutions with.

If you want to mess with toggle performance then go for it! I have some
homework I need to do anyway.

**Comment by SpaceOgre** [comment] 2016-04-01 17:51
Did some work on this tonight, separated parts of the ascendancy drawing code from the "normal" tree. Toggling is now significantly faster. It would probably be good to separate the rest as well and maybe tune the drawing code overall.

**Comment by EmmittJ** [comment] 2016-04-01 18:16
Yeah, I was going to mess around with drawing nodes and such in better
ways. Thanks for working on the separation.

**Comment by EmmittJ** [comment] 2016-04-01 19:06
Question, is there a benefit to using 'var' instead of the specified type? I noticed you changed a lot of those around.

**Comment by brather1ng** [comment] 2016-04-01 19:17
It's shorter, easier to type and easier to read (if the type is obvious) imo. But no, it has no real benefit (besides being required for some LINQ stuff, I think).

**Comment by EmmittJ** [comment] 2016-04-01 20:29
Thanks!

**Comment by SpaceOgre** [comment] 2016-04-01 21:27
It is a bit of both, some was probably changed automatically (I'm using ReSharper) and some I changed myself when I did the code changes. I like using it since it looks clean and I can more often than not understand the class from context :) 
But it is just a preference thing.

**Comment by EmmittJ** [comment] 2016-04-01 21:30
Ah, that makes sense!

**Comment by SpaceOgre** [comment] 2016-04-02 00:03
I noticed one more thing before: It is possible to skill nodes/get tool tip for nodes in the skilltree that are under the ascendancy tree. It would be good to disable this, maybe calculate circle area from the ascendancy center and if a node is in it don't show/skill the node?

**Comment by EmmittJ** [comment] 2016-04-02 00:06
Shouldn't be difficult. I am working on some more of the drawing stuff
(trying to cut down on what is called where). I will look into preventing
this

**Comment by EmmittJ** [comment] 2016-04-04 04:44
You guys think that we need any other ascendancy related features?

**Comment by SpaceOgre** [comment] 2016-04-04 09:04
Not that I can think of at the moment, except maybe go over the groupings and see if something needs to be moved around.

**Comment by EmmittJ** [comment] 2016-04-05 00:22
Groupings?

**Comment by SpaceOgre** [comment] 2016-04-05 08:08
I mean the attribut groups :)

**Comment by EmmittJ** [comment] 2016-04-05 17:03
Ah, I mostly grouped everything, but I didn't go over anything that was
already grouped.

**Comment by EmmittJ** [comment] 2016-04-05 20:08
Anyone know if we could add a filter for attributes like there is for
builds?

**Comment by SpaceOgre** [comment] 2016-04-06 08:05
It should be possible to solve it in more or less the same way, the problem might be with group interactions. We need to make sure that groups with all children hidden should be hidden as well. And then there is the challenge of creating a good UI for it :)

**Comment by EmmittJ** [comment] 2016-04-08 22:23
I have created the filter, but I am not sure it is in the best place since it will show when 'ItemList' and 'Item Attributes' are selected.

**Comment by EmmittJ** [comment] 2016-04-09 05:30
If no one has anything to add I will be hopefully pushing out a release in the next day or so

**Comment by SpaceOgre** [comment] 2016-04-09 09:01
Sounds good to me.

**Comment by brather1ng** [comment] 2016-04-09 20:31
Looks great!

One thing I noted: Some ascendancy nodes are difficult to unskill because regular nodes are right beneath them. This affects the Occultist's "Energy Shield, Chaos Damage" node (small node before Void Beacon), for example.

**Comment by EmmittJ** [comment] 2016-04-09 20:33
They shouldn't be be even be highlighted/clickable

**Comment by EmmittJ** [comment] 2016-04-09 20:34
Oh, I see what is happening. They aren't highlighted, but they are still
clickable

**Comment by brather1ng** [comment] 2016-04-09 20:37
If you mean the regular nodes, they are not highlighted, clickable or anything. They just block unskilling ascendancy nodes above them for some reason. I have to click the ascendancy node in an area where there is no regular node underneath. Skilling the ascendancy node and the to-be-unskilled-highlighting work fine, only the unskilling does not.

**Comment by EmmittJ** [comment] 2016-04-09 21:05
Alright, the latest commit should fix that issue

**Comment by brather1ng** [comment] 2016-04-09 21:12
Yep, looks good now.

**Comment by EmmittJ** [comment] 2016-04-10 01:30
Sweet! Thanks for catching those

**Comment by EmmittJ** [comment] 2016-04-10 22:55
Alright, I am going to right up some change log information and then push a release which should close this issue out :)

**Closed** 2016-04-11 04:30 UTC
Labels: discussion, important
