### ISSUE TITLE
Skill Tree Generator Broken

### ISSUE THREAD

**Issue by Shaod** [EmmittJ/PoESkillTree#369] opened 2016-09-11 14:52 UTC
I know you're super busy, and I doubt many people use this feature, but the skill tree generator is broken in several ways. I'm sure it's tempting to remove it, but for those of us that use it, it's awesome to find optimal and overlooked pathing routes.

Firstly, and probably most importantly, it returns invalid trees. It seems to do this the majority of times, at least if you add multiple points to path to.

![poeskilltree-generator2](https://cloud.githubusercontent.com/assets/22132367/18418068/3da2e656-7837-11e6-9431-f33fdcb3ae05.png)

Secondly, it doesn't respect the 'current tree as initial solution' option.

Thirdly, if you try to open the generator after you've already generated a skill it says that the window is already open, preventing you from running it again or tweaking results / weights.

![poeskilltree-generator1](https://cloud.githubusercontent.com/assets/22132367/18418078/6f03e880-7837-11e6-98b2-b20492faae41.png)

**Comment by brather1ng** [comment] 2016-09-11 15:29
1. Are you using any attribute or pseudo attribute constraints? If no, this is a known bug but not really relevant because using "Skill Tagged Nodes" does exactly the same thing and doesn't have that bug.
2. I will look into that.
3. That bug is fixed, the fix is just not yet released.

**Comment by Shaod** [comment] 2016-09-11 17:00
For 1, no I wasn't. Good to know there's an alternative, and thanks for the quick response.

**Comment by MLanghof** [comment] 2016-09-11 17:43
> I'm sure it's tempting to remove it
Not gonna happen, both brather1ing and me joined this project specifically to create it :)

**Comment by brather1ng** [comment] 2016-09-13 21:08
For 2, it does work from what I can see. It may not work in combination with 1, as those invalid tree may influence it.

As 1 is neither easy to fix nor really relevant, I'll close this. It has to be fixed at some point anyway, as it is caused by the interaction of the reductions (that are currently not used when constraints are present) and the final hill climbing step (which is not used when no constraints are present).

If I'm mistaken and you do find a situation where 2 occurs, feel free to reopen this.

**Closed by brather1ng** 2016-09-13 21:08 UTC
