### ISSUE TITLE
Version 2.4.1 crashes a lot

### ISSUE THREAD

**Issue by Tarsonis42** [EmmittJ/PoESkillTree#399] opened 2016-11-21 18:45 UTC
The new version is _very_ unstable for me. It crashes from random clicks or searches or trying to add new tree. I add my debug.txt. For example I have a reproducable crash trying to open this URL: 
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/604491/debug.txt)
http://poeurl.com/QMC

**Comment by Jinnai** [comment] 2016-11-21 21:46
Same issue here. Whenever I create a new top level build and load a tree there is a high chance for a crash. For example I have a reproducible crash trying to load this tree on a new top level tree:
https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAABAUBAQPuCaoMUg0fDXwOSA5cES8RUBGWEmkXHBhWGGoabBslHNwdFB1PHaodviL0Jogo-imLKwotHzLRM4c1uTwoQYdDyEVHRX5FnUZxSVFJsUuuTLNObU8EU1JWSFfJWAdboFxrXIpd8mh0aPJq-mwLbRlxeXgve9d8Dnzlf8aAMIKbgseDCYRIi4yPGo9Gj_qTJ5itmjua4Jtum6GcMpx7nL6drqEvpcSnCKcrp1WoubQMtzC4k76KwGbAmsHFw23K09Af1abXz9gk2VvZ_Npi2t3fhuGI5CLoWukC6rrr7uwY7TztYe-I7-vw1ffB99f5N_nd-ej-SQ==

[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/604860/debug.txt)

**Comment by SpaceOgre** [comment] 2016-11-22 07:30
This is a duplicate of #401 as far as I can tell.

**Closed by SpaceOgre** 2016-11-22 07:30 UTC
