### ISSUE TITLE
On program launch, error

### ISSUE THREAD

**Issue by MorsRage** [EmmittJ/PoESkillTree#195] opened 2015-07-24 18:23 UTC
I opened up the folder, double clicked the .exe and the program gave me an error.

Unfortunately I was clicking my mouse in the area and I hit "ok" before I could screen shot the error, but it was basically XML exception (0,0) something close to that, and now all my saved builds are gone.

I understand improvements to the calculator, but I've got to say not having an easy and portable file (at least I see no way to turn my old "persistant data.xml" file into some file in the new structure) makes this very concerning to me.

I've been using this program for years now and not once have I ever lost builds until this crash. If there are going to be these changes to file structures and how the program and files are run, I really strongly recommend a way to make sure builds are still saved in a file (I noticed other conversations about changing this).

If there is a persistent place in the new structure for the builds, please let me know and I'll recover them, but I couldn't find it.

**Comment by EmmittJ** [comment] 2015-07-24 18:53
1) XML exception (0,0) is when the XML is not in a valid XML format. Did you edit the PersistentData.xml file? 
2) I am not sure what you mean but new format. There hasn't been a new format since PersistentData.xml was introduced. 
3) What? Builds are always saved to a file...
4) There is no new structure

**Comment by MorsRage** [comment] 2015-07-24 18:58
So if I copy persistant xml over, it should work in the new folder? because when I tried that, no builds were loaded.

**Comment by EmmittJ** [comment] 2015-07-24 18:59
Can you upload your persistant information to something like PasteBin so that we can see what is causing the problem?

**Comment by Ttxman** [comment] 2015-07-24 19:06
@MorsRage If you used the new installer, persitentdata.xml location is now in your user/appdata/roaming/poeskilltree (or something like that). This is the only change to persistenddata.xml i can think of.

**Comment by EmmittJ** [comment] 2015-07-24 19:07
@Ttxman this is only with a full install. It looks like he is getting it in the right place if he is getting an error thrown when copying his old stuff to the correct location

**Comment by Ttxman** [comment] 2015-07-24 19:23
I'll saw lot of strange errors when using executables and archives downloaded from internet, they are usually blocked by UAC (smarts screen) and have messed up access rights to local files  (http://www.sevenforums.com/tutorials/124367-open-file-security-warning-unblock-file.html)?

**Comment by EmmittJ** [comment] 2015-07-24 19:25
That shouldn't happen any more (hopefully) with the installer.

**Comment by Ttxman** [comment] 2015-07-24 19:27
That depends on what @MorsRage downloaded and installed...

**Comment by MorsRage** [comment] 2015-07-24 22:21
Unfortunately I reinstalled to try and find the persistant.xml (without knowing it moved to roaming).

I installed in a new directory to not overwrite thinking perhaps that was the issue, so it overwrote that appdata\roam folder. 

I had copied the persist.xml into the actual install directory (where it was in previous versions) so it was doing nothing. So I just started editing new trees on the new version, and kept my old one in its old folder for reference.

It honestly it even more puzzling to me now that there was this error, because I never touched the appdata\roaming since I didn't know it was in there, sadly with it all gone now from a reinstall I don't think I have anything I can show you.

I now have my old trees into the newest version, by copying the old file into that location so at least that is solved. I lost some new builds but I can probably work them out.

**Comment by EmmittJ** [comment] 2015-07-24 22:26
> overwrote that appdata\roam folder. 
The installer won't overwrite files if they are present specifically it won't overwrite PersistentData.xml 
Sorry for your build loss, but there is nothing we can do without more information. I will take a look into why Persistent Data is being overwritten if it isn't loaded correctly though.

**Comment by MorsRage** [comment] 2015-07-25 02:45
Well I checked it, and it was missing the 6 builds that I theory crafted on the new install, that I can confirm, before I copy\pasted my old persistant.xml into that folder.

So as far as I can tell the odd crash I had deleted that data.

**Comment by l0g0sys** [comment] 2015-07-25 04:12
Can you discribe what you did?
Did you install PoESkillTree - The Awakening in Portable mode over old PoESkillTree 2.1.x version?

**Comment by MorsRage** [comment] 2015-07-25 04:40
I did not, I believe the last one or two installs have been the executables. 

That said, since emmit wasn't updating the tree at times during the Beta, I believe the first version was me updating the 1.3 - > 2.0 Beta tree myself, fixing some errors manually.

To get jewels to work I worked out some ad-hoc version with the chansuang\poedb (I think that is the same person) guy.

I'm trying to retrace what I did, but I can confirm that I did a "shit" version like I've always done for the Alpha testers for 2.0 launch, then at some point finally downloaded the poedb version, and then finally downloaded emmits, and I believe the executable(s) around launch.

Each version had its own folder, the most recent non beta executable is the first version where I couldn't find the builds file. I have at times had two versions of the calcs open, but I've been doing that for years and never had an issue.

Sorry I am not being not being more helpful, I've never had any issues with since emmit started doing his versions, so I wasn't expecting anything odd to happen.

**Comment by l0g0sys** [comment] 2015-07-25 05:03
Now i see. Yeah, lot of stuff happend :)
Well, all i can suggest you, is to use installer and choose different 
location than existing one. I'll add some additional check in selected 
installation location and disallow it when it's not possible to install 
over existing location.

There is no way to update/upgrade existing builds in same cases, that's 
why installer was made.
Installer either updates existing installation if it is possible or 
installs new version of application alongside existing one.

Regarding crash, i've noted it down and i'll make simple fix to avoid 
loss of data, even when XML file is invalid.

**Comment by MorsRage** [comment] 2015-07-25 22:12
The crash happened again. Do you want my xml file?

**Comment by EmmittJ** [comment] 2015-07-25 22:14
Yes, please.

**Comment by MorsRage** [comment] 2015-07-25 22:32
I can also compress all the files in the roaming folder, but the .xml file is blank, the last edit date is I guess when I turned off my computer.

Can I email the file or the .rar somewhere? I stopped using dropbox awhile ago, not sure where I would host the file for you to download.

**Comment by EmmittJ** [comment] 2015-07-25 23:15
1337erj1337@gmail.com if you really would like to email me.
Are you manually editing the persistent data file? Or shutting the program
done in a weird way?

**Comment by MorsRage** [comment] 2015-07-25 23:27
I don't manually edit anything, and I don't shut the program down when I turn my computer off, which I've never done and never had an issue. 

Normally the program just boots back up with the last thing I was doing.

hosted it on tinyupload

http://s000.tinyupload.com/?file_id=32888320543526567081

**Comment by MorsRage** [comment] 2015-07-25 23:29
http://s000.tinyupload.com/?file_id=02056618573453983980
 
original .xml file that I put into roaming to get all my builds

**Comment by EmmittJ** [comment] 2015-07-25 23:33
I can load that data perfectly fine. There must be something else going on
when saving. I will let @l0g0sys handle that since he said he has an idea
:P

**Comment by MorsRage** [comment] 2015-07-25 23:41
well wait, the xml file I showed you loads perfectly, I loaded it yesterday. It was only today when I opened up the program after making one build and turning off the computer that It crashed.

I can load the 2nd .xml file that is 18kb in size without issue.

**Comment by MorsRage** [comment] 2015-07-26 00:23
![xml error](https://cloud.githubusercontent.com/assets/13487815/8891941/085350de-330b-11e5-8f86-4dfea501866b.png)

Just a screen capture of the error message in case it matters.

**Comment by l0g0sys** [comment] 2015-07-26 05:01
That screen shot is just result of trying to load empty PersistendData.xml (0 bytes) (like the one from your RAR-ed AppData profile).
Question is how do you create empty XML file in the first place?
No way it can be created by application itself without any error message.

**Comment by l0g0sys** [comment] 2015-07-26 05:29
So, my conclusion is that you use other application (maybe our modified application built from 2.1.x version source files) which creates in some cases empty PersistentData.xml file (0 bytes size) and you just copy it over our 2.2.x version PersistentData.xml without noticing it being empty.
Then when you launch our 2.2.x application with this empty XML file, you will get this exception.

I'd suggest you to change the way you are trying to import your builds. What you are trying to do isn't even proper way to do it. And in the future i can guarantee you that this won't work for sure. I mean, just copying over application data files between incompatilble application versions. Use other application to just display tree and re-create tree by look in our 2.2.x application manually.

**Comment by MorsRage** [comment] 2015-07-26 05:40
I mean no offense, but I never had issues porting the trees over in this calc in the past (before you guys took over management of the app). Perhaps this is a super user experience, but if there is no way to port builds, or export them, or something between versions of the same skill tree.... I don't know what to say.

That said, I never put the .xml file in the roaming folder. I did not know it even existed since I don't follow the logic of separating what is in essence a small app for designing builds, but thats ok.

So I was resigned to the fact that I could not in fact port my builds in any efficient way, and was using the old version for reference, and only theorycrafting in the new version. It crashed, and I did a complete fresh install. It still crashed. Ill report back tomorrow if the tree fails to load when I boot up my computer.

**Comment by EmmittJ** [comment] 2015-07-26 05:45
All builds are saved in the PersistentData.xml file. That is how you
export/import builds.

The separation is done to conform to windows application structure. You
have install the portable version if you don't like it being in the roaming
folder.

Maybe try closing the application before turning off your computer.

**Comment by l0g0sys** [comment] 2015-07-26 06:11
No offense taken. I'm pretty sure we will make function to import builds in proper way, if it will be possible and there will be any meaning to it.

> if there is no way to port builds, or export them, or something between versions of the same skill tree...

Do you realise that tree changed between game patch 1.3.x and 2.0.x? Those are not same trees at all.
How do you expect us to port builds between 1.3.x and 2.0.x version, if even GGG can't make it, and they just force everyone to reset their trees.

Now, we didn't release this application with beta 2.0 tree. So there is no meaning for us to do any porting of previous builds possible at all. Why? Because last our version prior to our 2.2.0 version was version 2.1.3 working with 1.3 trees and those cannot be imported.

So if you use someone's else modified application, sorry, but it's not our fault that data produced by someone else aren't compatible with our version.

Just for the start, PersistendData.xml generated by our application always starts with &lt;StashBookmarks /&gt; element in XML file, which i cannot see in file you provided. So, it's not file generated by our application version 2.2.x at all.

Did you really install our 2.2.x version in new location (not just overwritting our 2.1.3 version or someone's else version), downloaded from this https://github.com/EmmittJ/PoESkillTree/releases project page?

**Comment by MorsRage** [comment] 2015-07-26 06:20
ok Good luck. I'm done trying to help.

**Comment by EmmittJ** [comment] 2015-07-26 06:21
You aren't exactly giving us any information that can help us. All we can
do is suggest ways of fixing the problem you are having.

**Comment by MorsRage** [comment] 2015-07-26 06:25
I'm not going to respond to insults.

Don't want me to use another version? Compile a version from Beta, the entire reason I spoke to Qarl on Alpha about getting tree designers into Alpha for the next version of the tree release.

Anyways, a clean install of the current version with nothing done by me except saving builds had that crash, twice now. Maybe its only my comp good luck.

**Comment by EmmittJ** [comment] 2015-07-26 06:30
No one is insulting you, but if you feel that way then sorry. The way the
beta data was sent out (generated by players) was incorrectly generated
anyway. It would have been more work to 'fix' the tree for beta then redo
all that same work a month later.

Are you closing the tree manually or are you letting shut down do it? It is
entirely possible that the program is not able to generate a valid xml file
in the time your computer takes to shut down.

**Comment by l0g0sys** [comment] 2015-07-26 06:34
I really didn't try to insult you in any way and nothing i wrote wasn't mean as insult.

Why don't you tell us the build causing the crash you are trying to save?
If you can reproduce it with only one build being added to Saved Builds, that would really help us.

But so far you provided one empty file, which ofcourse will cause exception on application launch, and 2nd file which works fine.

@EmmittJ You cannot cause crash with saving invalid Build without getting exception. Try to write some non-sense to Skill tree link and hit LOAD TREE. It will popup error. Then Exit applicaition and it will save erronous build into XML file. But when you launch application, it won't crash too, it will just popup error about wrong tree.

**Comment by l0g0sys** [comment] 2015-07-26 06:38
We won't be able to reproduce this until you can tell us exact steps how to do it.
Like:
1. Paste "xyz" into Skill tree link input.
2. Press LOAD TREE button.
3. "Save as..." build with Name "abc".
3. Exit application.
or something.

**Comment by EmmittJ** [comment] 2015-07-26 06:40
@l0g0sys I wasn't exactly talking about saving an invalid Build. I am
saying that there might be some race condition in which the
PersistentData.xml file is not being saved completely. If you try to load
an invalid xml doc (remove a close tag) you get the same error as shown
above.

**Comment by l0g0sys** [comment] 2015-07-26 06:44
@EmmittJ Yes, problem is, there no way to save such invalid file without noticing it (getting error popup) during saving build, at least none i know of atm. :)

**Comment by EmmittJ** [comment] 2015-07-26 06:46
@l0g0sys I don't know of one either, but it seems like that could be
possible

**Comment by l0g0sys** [comment] 2015-07-26 07:06
It is possible, but not **unnoticed**. If you ignore error popup and exit applicaiton without fixing the problem, then yes you can get unreadable XML file as result. But not without getting error message and telling you that there is something wrong.

**Comment by l0g0sys** [comment] 2015-07-26 07:16
Did just test of filling up the disk space to prove it :) Found 2GB USB stick and filled it up till last block after installing portable 2.2.2 version.

Kept adding builds with just skill tree URL until it tried to allocate next block on USB drive which wasn't available ofcourse, thus resulting in error during saving the build.

And all i got was this:
![save_build_not_enough_disk_space](https://cloud.githubusercontent.com/assets/8587407/8892916/7149ec0e-3376-11e5-80b7-66f0ece2a31b.png)

In english it means "Not enough disk space" or something like that in US Windows (i'm running Slovak Windows).

If you don't make enough space to save build without getting error, and you exit application ignoring that error, you will get invalid XML.
But if you free up some space, and save build again or exit application. No problem occurs.
No crash, nothing.

**Comment by zao** [comment] 2015-07-26 10:08
I've been running the same version since getting this program, somewhere before the culture invariance issue, something lower than 2.2.2.

The other night I lost my builds with this XML error. I'm not entirely certain, but I believe it was after my Windows 10 machine had automatically rebooted to install updates. This would imply that there might be some race conditions in saving data during forced shutdowns.

Have you considered saving the persistent data to a temporary file and atomically moving it over the old data file, or keeping a backup?

**Comment by MLanghof** [comment] 2015-07-26 11:07
@l0g0sys, I suppose nobody would see the error when it happens during 
system shutdown. So while you may be right that invalid xml is only 
generated when the app also informs you of the problem, nobody with this 
issue would get a warning before it's too late.

Saving the data in a temporary file next to the current one and only 
replacing one with the other once all data has been written should at 
least prevent losing all your builds.

**Comment by l0g0sys** [comment] 2015-07-27 05:04
@zao Thank a lot for more details, we can finally move somewhere with this issue :)

There should be no race condition during application data saving on exit anymore for single instance that is. I fixed double-saving before 2.2.0 release, but i'll check if it wasn't brought back by some merge.

But, what comes to mind is situation when you run 2 instances of application and both are trying to write application data on exit. That's where race condition can and most probably will occur.

I will do some testing of these scenarios.

I tought about general method to save files while preventing data loss for some time. Not only using temporary files, which brings lot of other issues, specifically error recovery and decision about validity of temporary file (temporary file can be saved just fine, but process can be stopped right before moving it over regular file, in this case temporary file is valid and has more recent data than original file). Also made some experimental CRC-aware streams, which could be used to write file and then check saved file's CRC against stream calculated CRC to ensure data integrity.

**Comment by l0g0sys** [comment] 2015-07-27 06:34
@zao can you tell us estimated size of your PersistenData.xml? Or how many builds you had? And did you get exactly same expcetion "error in XML document (0,0)"?

**Comment by zao** [comment] 2015-07-27 07:09
Yes, I got the exact same exception.
I had either two or three small builds, current filesize after re-importing two builds is just above 2k. I do not know what size it had prior to the fault.

My use-case for the tool is comparing in-progress build snapshots from forum threads to figure out where to go next, so I don't use any other feature of the program but storing builds and comparing them, so no crafting/item/stash/etc..

I can sadly not remember what the state of the file was while the error occured either, I've got a memory of finding a zero byte file, but I don't remember 100% if it was from this tool or in my own code around the same timeframe.

[Lazy 22pt](https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAAAwUBTwSb7Irkr2xo8vAfogALYcauxPavpz0PBjn7qvMGUWByqfcyrj5nm-RRfNk=) (maybe)
[Lazy 47pt](https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAAAwUBTwSb7Irkr2xo8vAfogALYcauxPavpz0PBjn7qvMGUWByqfcyrj5nm-RRUEfvDhQgXz8aPn7iPC2DzLc-_grYvTWStfJuqkrIPycqTQDuLOkVIC2DGbS-p2VNfNl5OQ==)
[Lazy 62pt](https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAAAwUBTwSb7Irkr2xo8vAfogALYcauxPavpxzOK1ANzf5UPQ8GOfuq8wZRYHKp9zKuPmeb5FFQR-8OFCBfPxo-fuJ5OTwtg8y3Pv4K2L01krXybqpKyD8nKk0A7izpFSAtgxm0vqdlTb02R36E2S_MwYK2imLshO_awXTtBS182Q==)

**Comment by l0g0sys** [comment] 2015-07-27 09:17
Well, things are getting even more interesting.

After 40+ OS reboots, i found out that App's class OnExit method override which saves PersistenData.xml file on application exit, in 99% cases isn't even invoked on Windows shutdown.

Only in 3 tests, when 3 application instances were being run simultaneously before OS shutdown, i've got successfully one of those 3 instances having PersistenData.xml written down without issue.
In all other cases the file wasn't event touched at all, due to OnExit method not being invoked.

So, chance that this issue is caused by Windows shutdown is almost zero, unless one is running multiple instances at same time, even then chance is higher that no data will be changed at all.

So now we have one more issue, make application actually write down data on Windows shutdown :)

**Comment by Ttxman** [comment] 2015-07-27 15:36
There is event raised when windows is shutting down or user logs off and applications are closed.
I think it is System.Win32.SystemEvents.SessionEnding or SessionEnded. Or you can add message filter to main window message queue and handle WM_EndSession or WM_QueryEndSession (i am not 100% sure the message names are right)

**Comment by l0g0sys** [comment] 2015-07-27 16:11
Yes, there is. And according to MSDN you don't have to handle it. Checked .NET source file of Application class and it's raising Exit event if SessionEnding event isn't explicitelly canceled, which ofc isn't if handler isn't even defined.

But what is puzzling that sometimes it is raised, but most of the time it isn't.

**Comment by Ttxman** [comment] 2015-07-27 16:31
i only know i ended up handling the message because form onclose was unreliable

**Comment by MLanghof** [comment] 2015-07-30 19:12
Just for the record, I also just experienced the invalid xml thing. I 
might have indeed shut down my PC while the app was active, didn't 
really keep track of it though.

**Comment by l0g0sys** [comment] 2015-07-31 04:32
Yep. After some research i discovered that behaviour i described earlier is actually bug only on Windows 7 x64 platform (maybe x86 as well). So, on other platforms OnExit is invoked and then there is possibility of process being killed by OS resulting in zero-length XML file.

Got some working prototype fo gracefull shutdown with workaround for Win7 bug and mutual exclusion for multi-instance scenarious. Will make pull request later today.

**Closed** 2015-08-02 19:59 UTC
