### ISSUE TITLE
Advanced Skill Tree Generator Crashing

### ISSUE THREAD

**Issue by Wolen** [EmmittJ/PoESkillTree#440] opened 2017-03-02 02:59 UTC
If I use more than 35 or so iterations the program will crash when it is about 90% done. 
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/812644/debug.txt)

**Comment by MLanghof** [comment] 2017-03-02 03:59
Huh, it's running out of memory. I'll see when I get around to debugging this.

**Comment by EmmittJ** [comment] 2017-03-02 04:46
Hmm, strange. I can't get it to even use more memory. I can max out my cpu
though.

**Comment by brather1ng** [comment] 2017-03-02 20:47
There's definitely a memory leak going on. The memory doesn't even get freed again when the generator is done.

**Comment by brather1ng** [comment] 2017-03-04 16:44
This is caused by the fitness cache in `GeneticAlgorithm`. There are a few million entries in it at 35 iterations. While each entry (a BitArray and a double) should only be a around 10 bytes, the overhead of objects and the `ConcurrentDictionary` leads to this being a few hundred MB in total.

I would call this intentional. Removing the cache is a 2-3 times slowdown. Maybe we could limit its size to like one million entires. Or we could just limit the amount of iterations to 20 or so.

Also, I couldn't get it to crash, even with 200 iterations. At ~105 iterations and 5GB RAM it got stuck for a short amount of time and lost 2GB. At 185 to 190 it got stuck multiple times, got up to 6.7GB RAM at one point and at the end it had basically starved everything else of RAM.

That the memory isn't freed has something to with the garbage collector. If the generator is run again, the memory of the previous run is freed eventually.

**Comment by MLanghof** [comment] 2017-03-05 17:08
Well, there we have one of the two hard problems for programmers:
- Cache invalidation
- Naming things
- Off-by-one errors

We could look into proper cache implementations (e.g. [MemoryCache](https://msdn.microsoft.com/en-us/library/system.runtime.caching.memorycache(v=vs.110).aspx)), and since our cached objects are not _that_ expensive to create we can even forego any locking. I do however feel like the overhead added by this is not worth it; it'd slightly improve this case at the expense of "normal" usage.

I dislike setting hard limits on the iteration counts - if that's the solution we're going for, it should just reset the cache every 20 (or however many) iterations. Reason being that users could just keep running 20 iterations again and again with the exact same effect, but making it needlessly tedious for them to compare results.

**Comment by brather1ng** [comment] 2017-03-05 18:06
Tested MemoryCache, it requires converting BitArrays to strings and is a lot slower than ConcurrentDictionary.

Actually, reseting the cache every iteration is a <10% slowdown, so that's seems to be a good solution.

**Comment by MLanghof** [comment] 2017-03-05 21:51
> Tested MemoryCache, it requires converting BitArrays to strings and is a lot slower than ConcurrentDictionary.

Thanks for testing, that confirms my suspicions.

>  reseting the cache every iteration is a <10% slowdown, so that's seems to be a good solution.

Nooo! That's a terrible solution for everybody with sufficient memory for the iteration counts he's doing.

**Comment by brather1ng** [comment] 2017-03-06 12:40
Hm, from my testing there was no noticeable difference between resetting the cache every iteration and keeping it. But only resetting it every x iterations is only like one line of code more.

The solver instance is not reused at all, so the cache is always deallocated. It just seems that the garbage collector takes some time to actually do that. I don't see how it could preserve the cache between runs.

**Comment by MLanghof** [comment] 2017-03-06 15:53
Oh man, I feel really stupid now. I forgot to reset the tree between solver runs - duh.

**Comment by MLanghof** [comment] 2017-03-06 17:06
I got around to doing my own tests and can only agree with you. I couldn't find a correlation between cache resets every iteration and increased calculation times. I guess "visibly" faster was just a confirmation bias (probably related to how it always speeds up towards the end of an iteration).

This is actually a very strong sign that the different iterations reliably explore different regions of the search space: Since the cache leads to 2-3x speed improvements, the average DNA is evaluated 2-3 times per iteration - but apparently that's focused on very few. If a significant portion of the DNA considered in each iteration were already seen in previous iterations, retaining the cache should also give significant speed improvements.

**Comment by MLanghof** [comment] 2017-03-06 18:03
I was curious about the hit counts, so I kept track of them.
[Here](https://gist.github.com/MLanghof/840dbd216314f9b456e31f4591f7aa19) is the distribution of successful hits over 9 iteration - without cache clear (but hit counts reset every iteration).
[Here's a chart!](https://i.imgur.com/D3yh5et.png)

It matches all the observations you've made so far:

- Most evaluations are saved for the very few DNAs with extreme hit counts - that's what makes removing the cache expensive.
- Overall, about 50% of evaluations hit the cache.
- About 90% DNA is only ever seen once, a figure that doesn't change much between iterations (while retaining the cache!). This is why resetting the cache is not a problem, 90% of the actual evaluations would happen regardless.

**Comment by Wolen** [comment] 2017-03-06 18:41
To clear up when it crashes, it crashes during when it gets stuck if I hit cancel. but I cannot recreate the crash anymore.

**Comment by brather1ng** [comment] 2017-03-06 23:16
Wow, suprises me that a few instances have that many hits.

I think that resetting the cache is not a problem can be kinda explained by the the search space being upwards of 2^300 instances big. With the amount of randomness that happens, different iterations will explore different parts of it, but the resulting trees may be similar (one tree can have many DNA representations because adding/removing some nodes to the DNA doesn't change the result of the minimal spanning tree).

> PS: It would be really cool to see how the shape of the distribution changes for different GA "internals" (age handling, % of population retained etc.)... Maybe one day.

Yeah, there is a lot stuff we could try out/evaluate. I'm more focused on the other parts of the program atm, so there won't be much in that direction from me in the near future.

(closing this issue as I fixed the memory issue (resetting every iteration))

**Closed by brather1ng** 2017-03-06 23:16 UTC
