### ISSUE TITLE
Skill tree generator does not open 2nd time, after its 1st run

### ISSUE THREAD

**Issue by NotKripp** [EmmittJ/PoESkillTree#378] opened 2016-09-22 04:40 UTC
Hello,
So, if after i run STG (skill tree generator), it will not open second time, information window will pop-up "the STG is already open". It is not opened though, there is no secondary window "hidden" under some PoESkillTree itself, or some other window.

The way to reproduce
1)Select tools -> nodes - STG. It does not matter whether its new build, or saved.
2)Press "Run". It does not matter which settings are chosen.
3)After generation complete, close progress bar, press X button to close STG window.
4)Select STG again -> information window will pop-up.

PS. On a completely side note - that design, when screen is divided in half (with 2 white areas on top and bottom) when opening settings for example, is really bad. Not only it takes a couple of second to play, it also flashes, which is really troublesome, considering whole colour theme is dark, and then, ther is suddenly a flash and 2 seconds later, 2 white patches.

**Comment by EmmittJ** [comment] 2016-09-22 04:53
First problem has been fixed, but it has not been released.

@brather1ng may have some more information on the 2nd issue.

**Comment by brather1ng** [comment] 2016-09-22 09:17
The dialog opening and closing animations have been shortened, there is only 200ms of animation now and the background overlay doesn't fade in and out but just is there.

The animation isn't flashing for me and I don't think it is too light in contrast with the background. Maybe the flashing is caused by the animation not being completely smooth? Anyway, that fading animation will be gone with the next release, so that should hopefully resolve your issue. If it doesn't, there isn't much we can do as the overlay comes from MahApps.Metro and can't be adjusted by us.

**Comment by EmmittJ** [comment] 2016-09-22 14:05
I haven't really been in a situation where the dialog boxes were too light,
but I use f.lux. I could see how white on the dark would be a bit
off-putting though.

**Comment by NotKripp** [comment] 2016-09-22 17:20
Thanks for answers.
Yeah, that second problem may not be PROBLEM, but it really bugged me out when i first saw it.
Thanks again.

**Comment by brather1ng** [comment] 2016-09-29 10:07
Closing as the fix was released.

**Closed by brather1ng** 2016-09-29 10:07 UTC
