### ISSUE TITLE
2.2.1 crash

### ISSUE THREAD

**Issue by lekne** [EmmittJ/PoESkillTree#182] opened 2015-07-19 10:38 UTC
When I try to run, it crashes. The debug.txt is as below:

The error time: 19.07.2015 13:19
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at POESKillTree.SkillTreeFiles.SkillTree.<set_Chartype>b__16(KeyValuePair`2 nd) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 486
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POESKillTree.SkillTreeFiles.SkillTree.set_Chartype(Int32 value) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 485
   at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 162
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
The error time: 19.07.2015 13:26
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at POESKillTree.SkillTreeFiles.SkillTree.<set_Chartype>b__16(KeyValuePair`2 nd) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 486
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POESKillTree.SkillTreeFiles.SkillTree.set_Chartype(Int32 value) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 485
   at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 162
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EmmittJ** [comment] 2015-07-19 15:46
Delete skilltree.txt in the data folder where you got the debug.txt file.
Make sure how have an internet connection. This will force it to
re-download the proper skill tree file, which I think is causing the
problem

**Comment by lekne** [comment] 2015-07-19 17:38
I deleted skilltree.txt as you said. When I run the program, first it downloaded the skill tree but again crashed. Below part is added to the debug.txt. Looks like it is the same error:

The error time: 19.07.2015 20:30
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at POESKillTree.SkillTreeFiles.SkillTree.<set_Chartype>b__16(KeyValuePair`2 nd) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 486
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at POESKillTree.SkillTreeFiles.SkillTree.set_Chartype(Int32 value) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\SkillTree.cs:line 485
   at POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:line 162
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EmmittJ** [comment] 2015-07-19 19:07
Can I ask how you updated the program? Have you tried running the installer
again?

**Comment by lekne** [comment] 2015-07-19 21:29
I have tried both, more than a few times actually. I don't understand why I have this problem. Now I am using the latest version from awakening beta.

**Comment by EmmittJ** [comment] 2015-07-19 21:48
The error is it is trying to change the Character type (Scion, Witch, etc.) and can't. 
In the folder where debug.txt is open up the file called `PersitentData.xml` and delete the '<CurrentBuild>' field. You might be trying to load a build that can't be used or is incorrectly formatted.

**Comment by brather1ng** [comment] 2015-07-19 22:11
Since it seems that more than one person has this problem, I investigated a bit and found a line that might be the problem, but definitely is not correct: in `MainWindow.xaml.cs:162`
```c#
Tree.Chartype =
    SkillTree.CharName.IndexOf(((string)((ComboBoxItem)cbCharType.SelectedItem).Name).ToUpper());
```
That line doesn't make much sense. It is run before the combo box is changed, meaning the value is always the default "Witch" (maybe except when people get the bug), meaning the index is always 0, which is the default anyway. Also CharName for Scion is "SEVEN" and for Shadow is "SIX", so it will break if one of those somehow gets into the combo box, because the corresponding combo box entries ("Scion", "Shadow") are not in the CharName array. This would lead to an ArgumentOutOfRangeException.

If I'd fix that in a pull request, is there a proper way for people that have this problem to download the compiled program and try it?

**Comment by EmmittJ** [comment] 2015-07-19 22:30
All that line is doing is grabbing and index, and if you run the debugger it will correctly grab that index. The problem is that the index that is being called upon isn't actually available (< 0 or > 6). Also, this shouldn't be a problem with just a few people. If there was a problem with switching the classes or getting a class name then it would effect everyone. Array access shouldn't be different for people.

**Comment by zao** [comment] 2015-07-19 22:35
Long guess, but in some locales like Turkish, uppercasing a lowercase dotted `i` results in `'LATIN CAPITAL LETTER I WITH DOT ABOVE' (U+0130)` `İ`, not our boring western dot-less `I`

You may want to consider `ToUpperInvariant(s)` or `ToUpper(s, CultureInfo.InvariantCulture)` if your alteration of text is not intended for linguistic purposes.

**Comment by brather1ng** [comment] 2015-07-19 22:40
Yep, it works fine with the debugger, because the combo box value should always be Witch at that point (I couldn't get it to be something different).
If the combo box for some reason is Scion or Shadow, IndexOf would return -1, because those are not in the CharName ("SEVEN" and "SIX" are in there), so Chartype would be set to -1, what leads to an ArgumentOutOfRangeException.

So at least the line doesn't make much sense because it is always Witch. It might also cause the described problem because it in some cases it may not be (it is this call to Chartype that produces the exception as seen in the debug output).

>Long guess, but in some locales like Turkish, uppercasing a lowercase dotted i results in 'LATIN CAPITAL LETTER I WITH DOT ABOVE' (U+0130) İ, not our boring western dot-less I

That sounds like it could more likely be the reason, would be solved by changing the line to `Tree.Chartype = 0` too (as it has no use as I described above).
We probably should also dig through the code for other cases were `ToUpper` could be a problem.

**Comment by EmmittJ** [comment] 2015-07-20 01:50
I am not sure if this is actually solved.

**Comment by EmmittJ** [comment] 2015-07-20 02:22
Could you please try using the installer that I have attached below and see if this solves the problem you are having? 

https://drive.google.com/file/d/0B2BWKeD5Id_gaEpTdGI2VDhOMzA/view?usp=sharing

**Comment by lekne** [comment] 2015-07-20 15:41
This works but every time at the start it gives the below error:

![poeskilltree2 2 2 error](https://cloud.githubusercontent.com/assets/13403002/8779934/a597f4a4-2f0e-11e5-9ead-0b00658e6600.png)

**Comment by lekne** [comment] 2015-07-20 15:48
There is another problem. Whenever I try to load a build with its link from the beta program, it gives the below error. But I can make new builds and save them.

![poeskilltree2 2 2 error2](https://cloud.githubusercontent.com/assets/13403002/8780144/c04afaa2-2f0f-11e5-9a36-aceb5fc407f4.png)

**Comment by SpaceOgre** [comment] 2015-07-20 16:34
The first one should be fix with my commit here: af4237bb192c702b135174eafeee27d31c317307, but I did that after @EmmittJ did the installer for you.

About the second problem: what do you mean with "link from the beta program"?

**Comment by lekne** [comment] 2015-07-20 16:54
I mean the build link generated at the bottom. I copy it from the version released for beta and paste it to the version @EmmittJ just linked.

**Comment by brather1ng** [comment] 2015-07-20 17:08
This is reproducable at least for me, so we should be able to fix that relatively fast (if it is not already fixed from the commits after the installer got created). I will look into it more in a bit.

The tree that is in the build link text box after the error has an additional slash before the base-64 part and the https gets changed to http. So in the meantime you can import trees by removing that additional slash after clicking load (after the error popup) or changing http to https before clicking load.
Before (copied from the old version):
http://www.pathofexile.com/passive-skill-tree/AAAAAgAA
After (copied into the new version and clicking load):
https://www.pathofexile.com/passive-skill-tree//AAAAAgAA

**Comment by brather1ng** [comment] 2015-07-20 18:08
I believe both problems were caused by a missing slash. I have that fixed in my pull request.
However the error message I got in the second case was the same as in the first, not the one you got. So I'm not entirely sure if that is completely fixed now, but at least for me it is.

**Comment by EmmittJ** [comment] 2015-07-20 19:36
Yes, both problems should be solved by removing the slash. It is because we have to pull the AAAAA... Sub string out of the URL. Adding extra characters makes it not able to process the URL. I will get you a new installer in a bit

**Comment by EmmittJ** [comment] 2015-07-20 20:12
https://drive.google.com/file/d/0B2BWKeD5Id_gbE9SWURLVzFqRzQ/view?usp=sharing

@lekne please try this version :)

**Comment by lekne** [comment] 2015-07-20 20:45
This is perfect. Thank you all guys for fixing this so fast.

**Comment by EmmittJ** [comment] 2015-07-20 20:46
Great! Thank you for the report :)

**Closed by EmmittJ** 2015-07-20 20:46 UTC
