### ISSUE TITLE
Freezes mouse and sometimes partially freezes keyboard.

### ISSUE THREAD

**Issue by Nhatorama** [EmmittJ/PoESkillTree#236] opened 2015-12-17 04:05 UTC
I'm using version 2.2.3.
If I launch the program, close it, and then launch it again, after it has finished loading my mouse will freeze. If I do a "Scan for hardware changes" in Device Manager, the mouse works again for a short while. Also at times my keyboard will partially freeze (some keys work, some don't) after the program has finished loading.

**Comment by EmmittJ** [comment] 2015-12-17 04:07
That doesn't sound like a problem that would be caused by our program.
There isn't anything that should change how your device works.

**Comment by Nhatorama** [comment] 2015-12-17 04:20
On my laptop it works fine so long as I tell my firewall to block Poeskilltree.exe from interacting with:
C:\\Windows\System32\wisptis.exe
C:\\Windows\system32\dwmapi.dll

My firewall (Comodo) log flags wisptis.exe with "Create Process" and
dwmapi.dll with "Install Hook"

**Comment by EmmittJ** [comment] 2015-12-17 04:46
Erm, there shouldn't be anything hooking into the application. Are you sure
your computer isn't infected? There is literally no reason why the
application would make your computer's mouse/keyboard to freeze.

**Comment by Nhatorama** [comment] 2015-12-17 05:39
Almost done scanning the computer.

**Comment by Nhatorama** [comment] 2015-12-17 08:02
A boot scan with Avast, and scans with superantispyware/malwarebytes antimalware didn't turn up any problems. I've updated windows with the latest patches and ran CCleaner and its registry cleaner.

I do think I found what the problem is though.
When Poeskilltree is launched, WISPTIS.EXE is added to the running processes.
If I close the first instance of Poeskilltree and open another one, a second entry of WISPTIS.EXE is added to the list of running processes and the mouse freezes.
The description for WISPTIS.EXE in the task manager says: "Microsoft Tablet PC Component".
I don't know why this process runs when I'm using WIndows 7 and I'm not using a touch screen monitor or anything related to tablets.

Does/can Poeskilltree be run on a tablet? (I'm guessing Windows 8 is the most likely candidate)
I like your program and I'm certainly not going to stop using because of such a minor (isolated?) issue, but I do hope you'll take a look at it or maybe offer some more advice on what the issue may be on my end.

Thanks

**Comment by EmmittJ** [comment] 2015-12-17 08:20
http://stackoverflow.com/questions/17111698/wpf-spawns-unwanted-wisptis-exe

These solutions might provide an answer. It seems to be a bug with one of
the .net frameworks. This isn't related to our program specificity.

**Comment by l0g0sys** [comment] 2015-12-17 08:26
Yeah, did some quick search too and found some issues with .NET 4.5.2 and pen input. Tho i don't have any issues, even i'm running .NET 4.5.2 on Win7 with Tablet PC feature enabled.

Try stopping Avast/Comodo or which anti-X programs you use, and run the PoESkillTree if issue occurs. It might be their intervention preventing the correct behaviour.

In the end, if you don't use tablet/pen input, then just disable this feature. Go to Control Panel => Programs => Programs and Features / Turn Windows features on or off => Uncheck Table PC Components.

**Comment by Nhatorama** [comment] 2015-12-17 09:05
I Turned off Tablet support, but that wasn't what made the issue go away.
In Comodo, WISPTIS.EXE was being automatically put in a sandbox by Comodo's Auto-Sandbox feature (which I don't remember enabling. It was probably enabled during the most recent update).
I've turned off the Auto-Sandbox feature and WISPTIS.EXE does not start with Poeskilltree anymore.
No more mouse freezing.

**Comment by EmmittJ** [comment] 2015-12-17 09:08
Alright, I will go ahead an close this issue then :)

**Closed by EmmittJ** 2015-12-17 09:08 UTC
