### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by Ilushia** [EmmittJ/PoESkillTree#344] opened 2016-07-14 12:52 UTC
So I managed to create a situation where the program crashes on loading. I believe this is happening because it's trying to load some kind of non-valid skill tree, but I'm not 100% sure on this.

I had been building a skill tree, and wanted to compare it to another off the net, so copied down the skill tree URL from the internet (This one if it matters: http://www.pathofexile.com/fullscreen-passive-skill-tree/AAAABAUCAQGRA5oEBwSzBx4I9A5IEZYV5xZvFr8W8xo4Gmwb8RzcHwIi9CSqJNgmPCaVJy8rJi3SL502xTbpOlg62DwFPV9DyEV8RZ1JUUmxTLNPBFJTU1JUR1VLVcZWSFugXfJfKmHiZlRo8mpDbAttGXFic7N1KnwOfsd_xoKbg9uFMoVthXuMNo8akFWTJ5Uul5WXl5f0mjua4J2unsSf36EvogCmvqcIp1Wu_bzqvorAVMBm0B_VgdWm18_YJNrd42rkIuWL6-Tr7uwu7DjtPO9874jv6_Af8Gvw1fk3-d0= ) and pasted it into the URL link, then realized I hadn't saved the skill tree yet, so did a save as and saved it, then loaded the other skill tree, which worked. I then activated the compare skill trees checkbox in order to look at how they differed, which didn't appear to work, not showing outlines or anything from the saved tree. Then I selected a different skill tree, which worked fine, then tried to re-load the saved skill tree, at which point the program crashed, and is now crashing on execution, presumably as it tries to load the corrupted skill tree.

Debug report is attached.
[debug.txt](https://github.com/EmmittJ/PoESkillTree/files/363730/debug.txt)

I also haven't been able to figure out where the program actually saves its skill trees, to try deleting the corrupted skill tree in order to be able to load the program again.

**Comment by EmmittJ** [comment] 2016-07-14 13:06
The location should be in one of these spots:
https://github.com/EmmittJ/PoESkillTree/wiki/How-To:-Copy-Builds

I will look into a fix later today.

**Comment by Ilushia** [comment] 2016-07-14 14:02
After going in a deleting both the current build and saved build for that tree, it now loads properly. Thanks for the help.

**Comment by brather1ng** [comment] 2016-09-10 15:47
As your linked build can be loaded and saved properly (this bug may have been fixed unintentionally), so I can't reproduce your issue, and your problem is fixed, I'll close this.

**Closed by brather1ng** 2016-09-10 15:47 UTC
