### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by CloudscrapeR86** [EmmittJ/PoESkillTree#342] opened 2016-07-01 21:30 UTC
I tried reinstalling and cleaning appdata/roaming but nothing seems to work.

The error time: 01/07/2016 23:30
Exception: System.IO.IOException: Il processo non può accedere al file 'C:\Users\CloudscrapeR\AppData\Roaming\PoESkillTree - Ascendancy\Items.xml' perché è in uso da un altro processo.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   in System.IO.StreamReader..ctor(String path)
   in POESKillTree.SkillTreeFiles.ItemDB.Load(String file, Boolean index) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\SkillTreeFiles\ItemDB.cs:riga 1384
   in POESKillTree.Views.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in c:\GitHub\PoESkillTree_Source\WPFSKillTree\Views\MainWindow.xaml.cs:riga 378
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   in System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   in System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   in System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   in System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   in MS.Internal.LoadedOrUnloadedOperation.DoWork()
   in System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   in System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   in System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   in System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   in System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   in System.Windows.Interop.HwndTarget.OnResize()
   in System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   in System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by brather1ng** [comment] 2016-07-01 21:37
Same as #334. Solution:

> If you download the latest zip release (no need to actually use that) and copy the Items.xml file from the zip into the folder specified in you debug log above, this crash should go away.

**Comment by CloudscrapeR86** [comment] 2016-07-01 21:49
Yup, it fixed that.

Any suggestion as to HOW to avoid it happening again? :)

**Comment by brather1ng** [comment] 2016-07-01 21:53
Well, this particular crash was probably caused by you cleaning AppData (and is fixed in the next release, though fiddling with that folder generally is not a good idea).

I have no idea what initially lead to crashes. So, if it happens again, please open an issue before you do anything so we can see the initial stack trace.

**Closed by brather1ng** 2016-07-01 21:53 UTC
