### ISSUE TITLE
Mixing of skill node representations

### ISSUE THREAD

**Issue by MLanghof** [EmmittJ/PoESkillTree#101] opened 2015-02-11 09:16 UTC
Currently, the code is kind of a mess with regards to what uses `ushort` and what uses `SkillNode` to represent skill nodes. Maybe this has legacy reasons, but it means that there's either code duplications or seemingly redundant conversion of node collections from one type to the other in a lot of places.

Are there objections to change everything to use `SkillNode` wherever possible?

**Comment by l0g0sys** [comment] 2015-02-11 09:34
It might be there for memory/speed purposes in general? As it might be 
more efficience to have dictionaries for node related metadata indexed 
by scalar value than object instance? Anyway, ushort identifier of node 
is used in skilltree URLs (encode/decode) if i remember it right, so I 
doubt you can completely remove use of ushort idenifier.
Think someone with more knowledge about SkillTree related stuff can 
answer you better than me :)

**Comment by MLanghof** [comment] 2015-02-11 10:05
Obviously, for parsing the json data it's necessary. That's why I said "wherever possible", not "remove entirely" ;)

-Memory concerns: The SkillNode instances all exist and sit in memory anyway. No memory is saved by using ushorts in random places, and you only pass around references to the instances.
-Speed concerns: I guess the pathfinding is (or was, until #98) the only thing for which speed is a concern, but it has to constantly look up nodes in the SkillNodes dictionary (since you need members like which neighbors the node has). Using references to the SkillNode instances (basically just an integer, albeit with a bit more overhead) really doesn't make a huge difference in my eyes.
-Node related metadata: Not yet used anywhere, everything already is in the SkillNode instances themselves.

If anything of this was a concern, benchmarks should be produced and bottlenecks identified.

But yeah, I'll wait if somebody has other objections.

**Comment by EmmittJ** [comment] 2015-02-11 17:21
If you can things from ushort then make sure that they encode correctly. I
honestly wouldn't mess with variable type unless they need to be. There is
a reason they are there. It's also proper to use smaller int values if you
aren't using the entire int.

Honestly, if it doesn't affect anything what is the point of changing it?
If it does need to be changed go ahead, but there are a lot of instances of
it.

**Comment by MLanghof** [comment] 2015-02-11 21:41
The only point in changing it is to avoid having to convert between both "references", especially for sets of them. If I have some time I'll look into it I'll see what I can do.

**Comment by Ttxman** [comment] 2015-02-19 12:01
To memory concerns - there are none :) 1500shorts is 3kB of memory. With .NET with WPF GUI there is something like 20MB loaded without any actual user code, memory optimizations of SkillTree are not necessary.

I had familiarized myself with the sourcecode in one afternoon, so i don't see a reason to change SkillTree/SkillNode handling. It would probably require massive changes in the code and it can itroduce lot of bugs.

But if you have some specific reason aside from "making the code nicer" I don't have problem with the change (but i would like to know the reason). 

There will be a performance hit, and it can be really large like 5x slower in some cases (2B struct vs. 4B (8B if CLR runs in as 64bit app) reference to an object and method call to access to 2B property). But we are talking about durations in nanoseconds so the perfomance hit shouldn't be a problem.

Ushorts in skill tree are heavily used with Hashsets for set operations. To correctly replace them you will probably need to make SkillNode behave same way as short. 
So SkillNode should be sealed immutable class with correctly overriden the GetHashcode, Equals, Implemented the IEquatable, IEquatable<> interfaces  the == and != operators etc. Created by some factory method to minimize duplication of assets.

Too much work for no significant gain :)

**Comment by MLanghof** [comment] 2015-02-19 13:59
"So SkillNode should be sealed immutable class with correctly overriden the GetHashcode, Equals, Implemented the IEquatable, IEquatable<> interfaces the == and != operators etc. Created by some factory method to minimize duplication of assets."
Is that really necessary for proper HashSet behavior? I'd have figured it constructs the hash table based on the pointer value, and since (at least currently) two SkillNodes are only equal if their references are equal (since every node exists only once).

I use lots of HashSets of class instances without that stuff in my [optimization code](https://github.com/MLanghof/PoESkillTree/blob/steiner/WPFSKillTree/SkillTreeFiles/SteinerTrees/MinimalSpanningTree.cs), and it appears to work fine.

Again, the reason would be "we wouldn't have to convert sets/lists of `ushort` element-wise into sets/lists of `SkillNode`". That's largely "making the code nicer", part "improving performance" (with gains as unknown atm as the resulting performance hit on the data structures). For the most part it would be "refactoring code" in my eyes.

**Comment by Ttxman** [comment] 2015-02-19 18:42
Yes you have to. It is expected behavior and only right way to make hashset/dictionary work on your type. And if you don't do it you will probably break some future code and tracking the issue will not be easy to repair, because no one will expect that hashset/dictionary is not working.

The real problem is future-proof implementation, there is no reason to change the current code if you just make changes that will probably need another pass of refactoring for some new feature. And you have to assume that the next programmer that will be editing you code will have inferior skill, so unexpected behavior is unacceptable  :)

First requirement is that hashcode cannot change during lifetime of object. Immutable object make this simple..
Second requirement is that if objects equals, their hashcodes equals.

Your code works, because you have only one set of unique objects that (accidentally) satisfy both conditions.

For example, imagine that you have added second algorithm for minimal spanning tree.
Now you want to run both algorithm in paralles and compare the 2 trees generated by the algorithms.
Easy way would be:

bool sametrees = MinimalSpanningTree1.mstNodes.SetEquals(MinimalSpanningTree1.mstNodes);

I have not read all your code, but this will not work if you are directly using constructors (without some caching) to make graph nodes from SkillTree, because they will have different hash codes, because they are different instances of "same node".

You can run into similar problems when trying to implement "difference between 2 skill trees" feature.

To make this work you have to satisfy both requirements.
The correct way is Immutable object with all that hashcode stuff..

The second possible way is making sure that each node have only single instance across whole domain. So you have to use factory method and some translation cache something like this:

public sealed class SkillNode
{
static Dictionary<ushort,SkillNode>  _nodeCache = ... //initialized at startup
static SkillNode(){ ..//static constructor init _nodeCache };
private SkillNode(){} //only private constructor
public static SkillNode GetNodeFor(ushort id)
{
    return nodeCache[id];
}
}

But this satisfies the conditions by "hack" (very unusual way), Factory methods are usually used for performance reasons and not to evade correct implementation :). 
AND implementing the immutable SkillNodes will not conflict with caching any way and solve some potential problems, so you should do it aqnyway :)

**Comment by MLanghof** [comment] 2015-02-19 22:33
I'll dutifully implement the equality comparison stuff (that example is a valid case I reckon). Although, (this)[http://stackoverflow.com/questions/8952003/how-does-hashset-compare-elements-for-equality] looks like only `GetHashCode()` and `Equals()` need to be overridden, at least for hash set usage. Where did you get your information from (the msdn page doesn't list any requirements at all)?

However, the conditions you listed are satisfied for `HashSet<SkillNode>` by virtue of everything not build-specific about the SkillTree being static, including the available SkillNodes. People would have to jump through a lot of hoops to break their usage of them in hash sets (the "hash code" of a SkillNode won't change since it only involves the reference itself, creating two different SkillNode instances that represent the same thing is... just useless with a static SkillTree).

**Comment by Ttxman** [comment] 2015-02-20 04:48
It is like two years ago i had massive problem with dictionaries and some 3rd party code. It took like 2 or 3 weeks to find the bug, so i read lot of articles around the web.... [this is pretty good advice](http://stackoverflow.com/questions/2890040/implementing-gethashcode). But the main source is msdn posts on implementing the "equals" and "== operator" and the generic versions of IEquatable /comparable interfaces and i got lot of information from [Eric Lipperts blog](http://ericlippert.com/2011/02/28/guidelines-and-rules-for-gethashcode/)

What kind of problem would making SkillNodes immutable solve? I don't have concrete example but  when you start messing with hashcode, Iequatable, etc.. immutable classes are easiest to implement, because you don't have to think about all the cases of object modification and how it will break the hashsets. Non immutable classes will be harder to implement, but there is no rule that the class used in hashset must be immutable..

**Comment by EmmittJ** [comment] 2016-09-02 04:08
Closing this as I don't think it matters too much. We are using SkillNode a lot more now.

**Closed by EmmittJ** 2016-09-02 04:08 UTC
